version: "3.9"

services:
  mysqldb:
    image: mysql:8.3
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: intership  # Update with your database name
    ports:
      - "3308:3306"  # Corrected port mapping for MySQL
    volumes:
      - db:/var/lib/mysql

  app-timesheet:
    depends_on:
      - mysqldb
    image: islemamor01/amorbackend:latest
    restart: on-failure
    ports:
      - "8089:8089"
    environment:
      SPRING_APPLICATION_JSON: >-
        {
          "spring.datasource.url": "jdbc:mysql://mysqldb:3306/intership?createDatabaseIfNotExist=true",
          "spring.datasource.username": "root",
          "spring.datasource.password": "root",  # Replace with actual secure password
          "spring.jpa.hibernate.ddl-auto": "update"
        }
    stdin_open: true
    tty: true

volumes:
  db:
