version: "3.8"

services:
  mysqldb:
    image: mysql:5.6
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: intership
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      mynetwork:
        ipv4_address: 172.18.0.2  # Specify the desired fixed IP address
  app:
    depends_on:
      - mysqldb
    image: islemamor01/intership:latest
    restart: on-failure
    ports:
      - "8089:8089"
    volumes:
      - .m2:/root/.m2

    stdin_open: true
    tty: true
    networks:
      mynetwork:
        ipv4_address: 172.18.0.3  # Specify a different fixed IP address

volumes:
  db:
networks:
  mynetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16