version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: intership
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      mynetwork:
        ipv4_address: 172.19.0.2  # Adresse IP pour MySQL

  app:
    depends_on:
      - mysqldb
    build: ./
    restart: on-failure
    ports:
      - "8089:8089"
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
    networks:
      mynetwork:
        ipv4_address: 172.19.0.3  # Adresse IP pour l'application

volumes:
  db:

networks:
  mynetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/16  # Plage IP pour éviter les conflits
