version: '3.1'
services:
  db:
    image: mysql
    container_name: mysqldb
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: intership
    networks:
      mynetwork:
        ipv4_address: 172.18.0.2  # Specify the desired fixed IP address

  back:
    depends_on:
      - db
    build: ./
    restart: on-failure
    ports:
      - "8083:8089"
    volumes:
      - .m2:/root/.m2
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/intership?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "root",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL8Dialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    stdin_open: true
    tty: true
    networks:
      mynetwork:
        ipv4_address: 172.18.0.3  # Specify a different fixed IP address

volumes:
  db:

networks:
  mynetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
