version: "3.8"

services:
  mysqldb:
    image: mysql:8.0.33  # Use a compatible MySQL version
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: intership
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    depends_on:
      - mysqldb
    image: islemamor01/intership:latest
    ports:
      - "8089:8089"
    volumes:
      - .m2:/root/.m2

volumes:
  db:
